stages:
  - build
  - build-image

build:
  stage: build
  image: node:16
  script:
    - npm install
    - npm run build
  cache:
    key:
      files:
        - package.json
        - package-lock.json
    paths:
      - node_modules/
  artifacts:
    expire_in: 5 days
    paths:
      - dist/*

build-image:
  stage: build-image
  when: on_success
  image: docker:24
  services:
    - docker:24-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    CONTAINER_CURRENT_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    CONTAINER_LATEST_IMAGE: $CI_REGISTRY_IMAGE:latest
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build --pull -t $CONTAINER_CURRENT_IMAGE .
    - docker tag $CONTAINER_CURRENT_IMAGE $CONTAINER_LATEST_IMAGE
    - docker push $CONTAINER_CURRENT_IMAGE
    - docker push $CONTAINER_LATEST_IMAGE